# Generated by Django 5.0.6 on 2024-05-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
