# Generated by Django 5.0.6 on 2024-05-29 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antstone_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancedetarea',
            name='foto',
        ),
        migrations.AddField(
            model_name='avancedetarea',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tareadeobra',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ImagenAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avances')),
                ('avance_de_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='antstone_api.avancedetarea')),
            ],
        ),
    ]
