# Generated by Django 5.0.2 on 2024-05-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessionaire_api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='capataz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='users.capataz'),
        ),
        migrations.AddField(
            model_name='obra',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='users.directordeobra'),
        ),
        migrations.AddField(
            model_name='tareadeobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='concessionaire_api.obra'),
        ),
        migrations.AddField(
            model_name='avancedeobra',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='concessionaire_api.tareadeobra'),
        ),
    ]
