# Generated by Django 5.0.2 on 2024-05-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaire_api', '0002_initial'),
        ('users', '0002_ayudantedealbanil_peon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='capataz',
        ),
        migrations.AddField(
            model_name='obra',
            name='gerente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='users.gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareadeobra',
            name='ayudantes_de_albanil',
            field=models.ManyToManyField(related_name='tareas', to='users.ayudantedealbanil'),
        ),
        migrations.AddField(
            model_name='tareadeobra',
            name='peones',
            field=models.ManyToManyField(related_name='tareas', to='users.peon'),
        ),
        migrations.CreateModel(
            name='AvanceDeTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('notas', models.TextField()),
                ('ubicacion_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ubicacion_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avances')),
                ('progreso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capataz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='users.capataz')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='concessionaire_api.tareadeobra')),
            ],
        ),
        migrations.DeleteModel(
            name='AvanceDeObra',
        ),
    ]
