export const AuthenticateEndpoint = "/token";
export const RefreshTokenEndpoint = "/refresh-token";
export const GetAyudanteDeAbanilEndpoint = "/users/ayudante-de-albanil/";
export const GetACapatazEndpoint = "/users/capataz/";
export const GetObrasEndpoint =  () => "/obras/";
export const PostObrasEndpoint = () =>  "/obras/";
export const GetAvancesEndpoint =  "/avances/";
export const PostAvancesEndpoint = () => "/avances/";
export const GetTareasEndpoint =  "/tareas/";
export const GetTareasByObraIdEndpoint = (obraId: number) => `obras/${obraId}/tareas/`;
